site_name: useful layers
repo_name: useful_layers
site_url: https://github.com/jernsting/useful_layers
site_dir: '../docs'

# Theme configuration
theme: 
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# extensions
markdown_extensions:
  - pymdownx.arithmatex
  - codehilite
  - admonition

# Site structure
nav: 
- Home: 'index.md'
- Layers:
  - Layers Introduction: 'layers/Layers.md'
  - Squeeze and Excitation: 'layers/squeeze_and_excitation.md'
  - Channel Attention: 'layers/channel_attention.md'
  - Spatial Attention: 'layers/spatial_attention.md'
- Blocks:
    - Block Introduction: 'blocks/Blocks.md'
    - ScalingBlock: 'blocks/ScalingBlock/ScalingBlock.md'
- Extending useful_layers: 'Extending.md'