# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: useful_layers build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    name: Run useful_layers tests and publish test coverage
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Install dependencies
      run: |
        pip install wheel flake8 
        python setup.py egg_info
        FILE=useful_layers.egg-info/requires.txt
        if test -f "$FILE"; then
        pip install torch pytest pytest-cov coveralls numpy -r useful_layers.egg-info/requires.txt
        else
        pip install torch pytest pytest-cov coveralls numpy
        fi
        pip install .
         
    - name: Test with pytest
      run: |
        PYTHONPATH=./ pytest ./test --cov=./useful_layers
    - name: Coveralls
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
